config/routes.rb
Rails.application.routes.draw do
  resources :enrollments, only: [:index]

  root "pages#home"

  get 'profile', to: 'pages#profile'
  get 'manage_trainers', to: 'pages#manage_trainers'
  get 'manage_trainees', to: 'pages#manage_trainees'
  get 'manage_courses', to: 'pages#manage_courses'
  delete 'destroy_trainer/:trainer_id', to: 'pages#destroy_trainer', as: 'destroy_trainer'
  delete 'destroy_trainee/:trainee_id', to: 'pages#destroy_trainee', as: 'destroy_trainee'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  resources :courses do
    member do
      post 'enroll'
      delete 'unenroll'
      delete 'remove_trainee/:trainee_id', to: 'courses#remove_trainee', as: 'remove_trainee'
    end
  
    # Nested routes for comments inside courses
    resources :comments
  end
  

  # Batches and their tasks
  resources :batches do
    post 'add_trainee', on: :member
    resources :tasks do
      member do
        patch 'update_status', to: 'tasks#update_status'
      end
    end
    get 'track_tasks', to: 'tasks#track_tasks', as: 'track_tasks'
  end
  

  get 'tasks_assigned', to: 'tasks#index', as: 'tasks_assigned'
  
  get 'my_courses', to: 'courses#my_courses', as: 'my_courses'
  get 'manage_all_trainees', to: 'courses#manage_all_trainees', as: 'manage_all_trainees'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :batch
  belongs_to :trainee, class_name: 'User', foreign_key: 'user_id'
  belongs_to :trainer, class_name: 'User', foreign_key: 'trainer_id', dependent: :destroy

  has_one_attached :resource, dependent: :destroy

  scope :filter_tasks, ->(status) { where.not(status: status)}

  validates :name, :description, :deadline, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_batch, only: [:new, :create]
  before_action :set_task, only: [:show, :update_status]

  def new
    @task = Task.new
    @trainees = @batch.users.show_trainees 
  end

  def index
    if current_user.trainee?
      @assigned_tasks = current_user.tasks.filter_tasks(2)
    else
      redirect_to root_path, alert: 'failed'
    end
  end

  def show
    @resource = @task.resource if @task.resource.attached?
  end

  def create
    @task = @batch.tasks.build(task_params)
    @task.trainer = current_user

    if @task.save
      redirect_to batch_path(@batch), notice: "Task has been assigned successfully"
    else
      render :new, alert: "Failed to create a task"
    end
  end

  def update_status
    if current_user.trainee? && @task.update(task_status_params)
      if @task.status.to_i == 2
        redirect_to tasks_assigned_path, notice: 'Task status updated successfully'
      else
        redirect_to batch_task_path(@task.batch, @task), notice: 'Task status updated successfully'
      end
    else
      redirect_to batch_task_path(@task.batch, @task), alert: 'Failed to update task status'
    end
  end

  def track_tasks
    @batch = Batch.find(params[:batch_id])

    if current_user.trainer?
      @trainee_tasks = @batch.tasks.includes(:trainee)
    else
      redirect_to root_path, alert: 'Access denied'
    end
  end

  private

  def set_batch
    @batch = Batch.find(params[:batch_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_status_params
    params.require(:task).permit(:status)
  end

  def task_params
    params.require(:task).permit(:name, :description, :deadline, :status, :resource, :user_id, :trainer_id)
  end
end

app/views/tasks/index.html.erb
<div class="task-container">
    <div class="tasks">
        <% if @assigned_tasks.length > 0 %>
            <% @assigned_tasks.each do |task| %>
                <div class="task">
                    <div class="task-header">
                        <p><span class="highlight-text">Task:</span> <%= task.name %></p>
                        <%= link_to 'Details', batch_task_path(task.batch, task.id) %>
                    </div>
                    <div class="task-body">
                        <p>Task Description: <%= task.description %></p>
                        <p class="task-deadline">Deadline: <%= task.deadline.strftime("%m/%d/%Y") %></p>
                    </div>

                    <div class="task-footer">
                        <span class="task-status">
                            <strong>Status:</strong> <%= task.status.to_i == 0 ? "Pending" : task.status.to_i == 1 ? "In Progress" : "Completed" %>
                        </span>
                        <span class="task-created">Assigned on: <%= task.created_at.strftime("%m/%d/%Y") %></span>
                    </div>
                </div>
            <% end %>
        <% else %>
            <p>There is no tasks assigned to you...!</p>
        <% end %>
        
    </div>
</div>

app/views/tasks/new.html.erb
<div class="task-container">
    <%= form_with(model: @task, url: batch_tasks_path(@batch), local: true, data: { turbo: false }) do |form| %>
        <div>
            <%= form.label :name, "Task Name" %>
            <%= form.text_field :name %>
        </div>

        <div>
            <%= form.label :description, "Task Description" %>
            <%= form.text_area :description %>
        </div>

        <div class="form-group">
            <%= form.label :deadline, "Deadline" %>
            <%= form.datetime_select :deadline %>
        </div>

        <div>
            <%= form.label :status, "Status" %>
            <%= form.select :status, options_for_select([['Pending', 0], ['In Progress', 1], ['Completed', 2]]), {}, class: 'role-dropdown' %>
        </div>

        <div>
            <%= form.label :resource, "Attach a Resource (PDF/Image)" %>
            <%= form.file_field :resource, class: "form-control" %>
        </div>
        
        <%= hidden_field_tag('task[user_id]', params[:trainee_id]) %>
        <%= hidden_field_tag('task[trainer_id]', @batch.user.id) %>
        
        <div>
            <%= form.submit "Assign Task", class: 'btn btn-enroll' %>
        </div>
    <% end %>
</div>

app/views/tasks/show.html.erb
<div class="task-container">
    <div class="task-details">
        <h2>Task: <%= @task.name %></h2>
        <p><strong>Description:</strong> <%= @task.description %></p>
        <p><strong>Deadline:</strong> <%= @task.deadline.strftime("%m/%d/%Y") %></p>
        <p><strong>Status:</strong> <%= @task.status.to_i == 0 ? "Pending" : @task.status.to_i == 1 ? "In Progress" : "Completed" %></p>
        <p><strong>Created on:</strong> <%= @task.created_at.strftime("%m/%d/%Y") %></p>

        <% if @task.resource.attached? %>
            <p>
                <strong>Resource:</strong>
                <%= link_to 'Download Resource', rails_blob_path(@task.resource, disposition: "attachment") %>
            </p>
        <% end %>

        <div class="task-status-form">
            <%= form_with(model: @task, url: update_status_batch_task_path(@task.batch, @task), method: :patch, local: true) do |f| %>
                <div class="form-group">
                <%= f.label :status, "Change Task Status" %>
                <%= f.select :status, options_for_select([['Pending', 0], ['In Progress', 1], ['Completed', 2]], @task.status), class: 'role-dropdown' %>
                </div>
                <div class="form-group">
                <%= f.submit 'Update Status', class: 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/tasks/track_tasks.html.erb
<div class="task-container">
  <h1>Track Tasks</h1>

  <% if @trainee_tasks.any? %>
    <table class="content-table">
      <thead>
        <tr>
          <th>Trainee</th>
          <th>Task Name</th>
          <th>Status</th>
          <th>Deadline</th>
        </tr>
      </thead>
      <tbody>
        <% @trainee_tasks.each do |task| %>
          <tr>
            <td><%= task.trainee.full_name if task.trainee %></td>
            <td><%= task.name %></td>
            <td><%= task.status.to_i == 2 ? "Completed" : (task.status.to_i == 1 ? "In Progress" : "Pending") %></td>
            <td><%= task.deadline.strftime('%m/%d/%Y') if task.deadline %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No tasks assigned to your trainees at this time.</p>
  <% end %>
</div>