config/routes.rb
Rails.application.routes.draw do
  resources :enrollments, only: [:index]

  root "pages#home"

  get 'profile', to: 'pages#profile'
  get 'manage_trainers', to: 'pages#manage_trainers'
  get 'manage_trainees', to: 'pages#manage_trainees'
  get 'manage_courses', to: 'pages#manage_courses'
  delete 'destroy_trainer/:trainer_id', to: 'pages#destroy_trainer', as: 'destroy_trainer'
  delete 'destroy_trainee/:trainee_id', to: 'pages#destroy_trainee', as: 'destroy_trainee'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  resources :courses do
    member do
      post 'enroll'
      delete 'unenroll'
      delete 'remove_trainee/:trainee_id', to: 'courses#remove_trainee', as: 'remove_trainee'
    end
  
    # Nested routes for comments inside courses
    resources :comments
  end
  

  # Batches and their tasks
  resources :batches do
    post 'add_trainee', on: :member
    resources :tasks do
      member do
        patch 'update_status', to: 'tasks#update_status'
      end
    end
    get 'track_tasks', to: 'tasks#track_tasks', as: 'track_tasks'
  end
  

  get 'tasks_assigned', to: 'tasks#index', as: 'tasks_assigned'
  
  get 'my_courses', to: 'courses#my_courses', as: 'my_courses'
  get 'manage_all_trainees', to: 'courses#manage_all_trainees', as: 'manage_all_trainees'
end

app/views/pages/home.html.erb
<section class="hero-section">
    <div class="hero-section-content">
        <div class="intro-section">
            <div class="intro-content">
                <p class="intro-title">Experience the <span class="highlight-text">Ultimate</span></p>
                <p class="intro-sub-title">Developers Community</p>
            </div>
            <div class="intro-slogan">
                <p>Join the <span class="highlight-text">leading platform</span> where developers <span class="highlight-text">thrive</span> by connecting, learning, and collaborating. Unlock your full potential and become part of a community that <span class="highlight-text">innovates</span> and drives the future of technology.</p>
            </div>
            <div class="explore-more">
                <%= link_to "Explore More", new_user_registration_path, class: "btn explore-btn" %>
            </div>
        </div>
        <div class="banner-image-container">
            <%= image_tag "bannerimage.png", class: 'banner-img' %>
        </div>
    </div>
</section>

<section class="how-it-works">
    <div class="works-content">
        <div class="works-title">
            <h2>How It Works</h2>
        </div>

        <div class="grid-content">
            <!-- Signup Section -->
            <div class="signup-content">
                <i class="ph ph-user-plus"></i>
                <h3>Sign Up</h3>
                <p class="signup-desc">Create your account to join our community and access a wide range of resources tailored for developers like you.</p>
            </div>

            <!-- View Courses Section -->
            <div class="courses-content">
                <i class="ph ph-book-open"></i>
                <h3>Explore Courses</h3>
                <p class="courses-desc">Browse through a diverse selection of courses designed to enhance your skills and keep you updated with the latest trends.</p>
            </div>

            <!-- View Batches Section -->
            <div class="batches-content">
                <i class="ph ph-calendar"></i>
                <h3>Enroll in Batches</h3>
                <p class="batches-desc">Select from various batch timings that suit your schedule and learn at your own pace with like-minded peers.</p>
            </div>
        </div>
    </div>
</section>

app/views/pages/manage_trainees.html.erb
<div class="trainees-container">
  <h1>Manage All Trainees</h1>

    <% if @trainees.any? %>
        <table class="content-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Enrolled Courses</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @trainees.each do |trainee| %>
                    <tr>
                        <td><%= trainee.first_name %></td>
                        <td><%= trainee.email %></td>
                        <td>
                            <% if trainee.enrolled_courses.any? %>
                                <%= trainee.enrolled_courses.map(&:name).join(', ') %>
                            <% else %>
                                -
                            <% end %>
                        </td>
                        <td>
                            <%= link_to 'Remove Trainer', destroy_trainee_path(trainee.id), data: { turbo_method: "Are you sure you want to remove this trainer", turbo_method: :delete }, class: "btn btn-remove" %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
    <% else %>
        <p>No trainers available.</p>
    <% end %>
</div>

app/views/pages/manage_trainers.html.erb
<div class="trainees-container">
  <h1>Manage Trainers for All Courses</h1>

    <% if @trainers.any? %>
        <table class="content-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Created Courses</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @trainers.each do |trainer| %>
                    <tr>
                        <td><%= trainer.first_name %></td>
                        <td><%= trainer.email %></td>
                        <td>
                            <% if trainer.created_courses.any? %>
                                <%= trainer.created_courses.map(&:name).join(', ') %>
                            <% else %>
                                -
                            <% end %>
                        </td>
                        <td>
                            <%= link_to 'Remove Trainer', destroy_trainer_path(trainer.id), data: { turbo_confirm: "Are you sure you want to remove this trainer", turbo_method: :delete }, class: "btn btn-remove" %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
    <% else %>
        <p>No trainers available.</p>
    <% end %>
</div>

app/views/pages/profile.html.erb
<div class="profile-box-container">
    <div class="profile-header">
        <i class="ph ph-user-circle"></i>
        <h2 class="profile-header-title">
            <%= current_user.first_name %> <%= current_user.last_name %> (<%= current_user.role %>)
        </h2>
    </div>

    <div class="profile-body">
        <div class="profile">
            <label>First Name</label>
            <h4><%= current_user.first_name %></h4>
        </div>
        <div class="profile">
            <label>Last Name</label>
            <h4><%= current_user.last_name %></h4>
        </div>
        <div class="profile">
            <label>Your Email</label>
            <h4><%= current_user.email %></h4>
        </div>
        <div class="profile">
            <label>Joinint Date</label>
            <h4><%= current_user.joining_date %></h4>
        </div>
        <div class="profile">
            <label>Phone Number</label>
            <h4><%= current_user.phone_number %></h4>
        </div>
        <div class="profile">
            <label>Address</label>
            <h4><%= current_user.address %></h4>
        </div>
        <div class="profile">
            <label>Pincode</label>
            <h4><%= current_user.pincode %></h4>
        </div>
        <div class="profile">
            <label>Latest Degree</label>
            <h4><%= current_user.latest_degree %></h4>
        </div>
    </div>

    <div class="profile-footer">
        <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-edit' %>
        

        <%= link_to 'Delete Profile', destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-delete-profile" %>
    </div>
</div>