config/routes.rb
Rails.application.routes.draw do
  resources :enrollments, only: [:index]

  root "pages#home"

  get 'profile', to: 'pages#profile'
  get 'manage_trainers', to: 'pages#manage_trainers'
  get 'manage_trainees', to: 'pages#manage_trainees'
  get 'manage_courses', to: 'pages#manage_courses'
  delete 'destroy_trainer/:trainer_id', to: 'pages#destroy_trainer', as: 'destroy_trainer'
  delete 'destroy_trainee/:trainee_id', to: 'pages#destroy_trainee', as: 'destroy_trainee'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  resources :courses do
    member do
      post 'enroll'
      delete 'unenroll'
      delete 'remove_trainee/:trainee_id', to: 'courses#remove_trainee', as: 'remove_trainee'
    end
  
    # Nested routes for comments inside courses
    resources :comments
  end
  

  # Batches and their tasks
  resources :batches do
    post 'add_trainee', on: :member
    resources :tasks do
      member do
        patch 'update_status', to: 'tasks#update_status'
      end
    end
    get 'track_tasks', to: 'tasks#track_tasks', as: 'track_tasks'
  end
  

  get 'tasks_assigned', to: 'tasks#index', as: 'tasks_assigned'
  
  get 'my_courses', to: 'courses#my_courses', as: 'my_courses'
  get 'manage_all_trainees', to: 'courses#manage_all_trainees', as: 'manage_all_trainees'
end

app/models/batch.rb
class Batch < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user
  belongs_to :course
  # belongs_to :comment

  # has_and_belongs_to_many :users
  has_many :batch_users, dependent: :destroy
  has_many :users, through: :batch_users, dependent: :destroy
  # 

  validates :name, :description, :start_date, :end_date, :duration, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  # Associations: users <==> courses
  belongs_to :trainer, class_name: "User", foreign_key: :user_id
  
  belongs_to :user

  # Automatically delete enrollments when a course is deleted
  has_many :enrollments, dependent: :destroy
  has_many :trainees, through: :enrollments, source: :user

  has_one_attached :image, dependent: :destroy

  # comment section associations
  has_many :comments, dependent: :destroy

  validates :name, :duration, :description, :category, :level, :start_date, :end_date, presence: true
  validate :image_type_validation


  # Associations for batches
  has_many :batches, dependent: :destroy

  private

  def image_type_validation
    if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
      errors.add(:image, 'must be a JPEG or PNG')
    elsif image.attached? == false
      errors.add(:image, 'must be attached')
    end
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :authenticate_user! 
  before_action :get_batches, only: [:index, :show]
  
  def index
  end

  def new
    @batch = Batch.new
    @courses = current_user.created_courses
  end

  def show
    @batch = Batch.find(params[:id])
    @trainees = @batch.users.show_trainees
  end
  

  def create
    @batch = Batch.new(batch_params)
    @batch.user = current_user
      
    @batch.course_id = params[:batch][:course_id] if params[:batch][:course_id].present?
    @batch.comment_id = params[:batch][:comment_id] if params[:batch][:comment_id].present?
    
    if @batch.save
      current_user.batches << @batch
      redirect_to batches_path, notice: 'Batch was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end
  

  def edit
  end
  
  def update
  end

  def destroy
    @batch = Batch.find(params[:id])
  
    binding.pry
    
    if @batch.destroy
      redirect_to batches_path, notice: 'Batch was successfully deleted.'
    else
      redirect_to batches_path, alert: 'Failed to delete the batch.'
    end
  end
  

  def add_trainee
    @batch = Batch.find(params[:id])
    trainee_ids = params[:batch] ? params[:batch][:trainee_ids] : []
  
    if trainee_ids.present?
      trainees = User.where(id: trainee_ids)
      
      @existing_trainees = @batch.users.where(id: trainee_ids)
  
      if @existing_trainees.any?
        redirect_to @batch, notice: 'trainee is already assigned.'
        return
      end
      
      new_trainees = trainees - @existing_trainees
      @batch.users << new_trainees if new_trainees.any?
  
      redirect_to @batch, notice: 'Trainees were successfully added.'
    else
      redirect_to @batch, alert: 'No trainees selected.'
    end
  end

  # private

  def batch_params
    params.require(:batch).permit(:name, :description, :start_date, :end_date, :duration)
  end

  def get_batches
    @batches = current_user.batches
  end
  
end

app/views/batches/add_trainee.html.erb
<%= form_with url: add_trainee_batch_path(@batches), method: :post do |form| %>
    <%= form.label :trainee_ids, "Select Trainees to Add to Batch" %>
    <%= form.collection_select :trainee_ids, @trainees, :id, :full_name, {}, multiple: true %> 
    <%= form.submit "Add Trainees" %>
<% end %>

app/views/batches/index.html.erb
<div class="batch-container">
    <div class="batch-header">
        <h1>All Batches</h1>
        <%= link_to "Create A Batch", new_batch_path, class: "btn, btn-batch" %>
    </div>

    <div class="batch-content">
        <% if @batches.length > 0 %>
            <% @batches.each do |batch| %>
                <div class="batch-body">
                    <div class="batch-title">
                        <h3>Instructor Name: <%= batch.user.first_name %></h3>
                        <span>Best Seller</span>
                    </div>
                    <div class="batch-inner-body">
                        <p class="">Batch Name: <%= batch.name %></p>
                        <p class="">Description: <%= batch.description %></p>
                        <p class="">Duration: <%= batch.duration %></p>
                        <p class="">Course: <%= batch.course.name %></p>
                        <span>Start date: <%= batch.start_date %></span>
                        <span>End date: <%= batch.end_date %></span>
                    </div>
                        <%= link_to "View Batch", batch_path(batch), class: "btn-view-batch" %>
                    </div>
            <% end %>
        <% else %>
            <p>No Any Batches Created yet.</p>
        <% end %>
    </div>
</div>  

app/views/batches/new.html.erb
<div class="batch-container">
  <div class="batch-header">
    <h2 class="highlight-text">Create A Batch</h2>
  </div>

  <div class="batch-form">
    <% if @batch.errors.any? %>
        <div class="error-messages">
            <h2><%= pluralize(@batch.errors.count, "error") %> prevented this batch from being saved:</h2>
            <ul>
            <% @batch.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <%= form_with(model: @batch, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :name, "Batch Name" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Enter batch name" %>
      </div>

      <div class="form-group">
        <%= form.label :description, "Batch Description" %>
        <%= form.text_area :description, class: "form-control", placeholder: "Enter batch description" %>
      </div>

      <div class="form-group">
        <%= form.label :start_date, "Start Date" %>
        <%= form.date_field :start_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :end_date, "End Date" %>
        <%= form.date_field :end_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :duration, "Duration (in days)" %>
        <%= form.number_field :duration, class: "form-control", placeholder: "Enter duration" %>
      </div>

      <div class="form-group">
        <%= form.label :course_id, "Course" %>
        <%= form.select :course_id, options_from_collection_for_select(@courses, :id, :name), { include_blank: 'Select Course' }, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= form.submit "Create Batch", class: "btn btn-enroll" %>
      </div>
    <% end %>
  </div>
</div>

app/views/batches/show.html.erb
<div class="batch-container">
  <div class="batch-show-info">
    <div>
      <h2>Batch Information</h2>
      <p><strong>Name:</strong> <%= @batch.name %></p>
      <p><strong>Course:</strong> <%= @batch.course.name %></p>
      <p><strong>Description:</strong> <%= @batch.description %></p>
      <p><strong>Start Date:</strong> <%= @batch.start_date %></p>
      <p><strong>End Date:</strong> <%= @batch.end_date %></p>
    </div>

    <div class="batches-data">
      <h2>Add Trainees</h2>
      <%= form_with(model: @batch, url: add_trainee_batch_path(@batch), method: :post, local: true) do |form| %>
        <%= form.label :trainee_ids, "Select Trainees to Add to Batch" %>
        
        <%= form.select :trainee_ids, options_for_select([["Select options", "", { disabled: true, selected: true }]] + @trainees.map { |t| [t.first_name, t.id] }), {}, class: "role-dropdown" %>
        
        <%= form.submit "Add Trainees", class: "btn batches-btn" %>
      <% end %>
    </div>


    <div class="all-trainees">
      <h3 class="trainee-title">All Trainees</h3>
      <% @batch.users.show_trainees.each do |trainee| %>
        <div class="trainee-info">
          <p><%= trainee.full_name %></p>
          <%= link_to 'Assign Task', new_batch_task_path(@batch, {trainee_id: trainee.id}), class: 'btn btn-enroll' %>
        </div>
      <% end %>
    </div>
  </div>
</div>